---
title: "project_v1"
author: "Pranjal Maheshka, Asha Christensen, Marco Navarro"
date: "2023-04-24"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(rsample)
library(caret)
library(tidyverse)
library(rpart)
library(rpart.plot)
library(rsample) 
library(randomForest)
library(lubridate)
library(modelr)
knitr::opts_chunk$set(echo = TRUE)

setwd = ("C:/Users/pranj/Documents/Final-Project-Data/") #Pranjal
opioid_df = read.csv("data/data_final.csv") 
```

## R Markdown


```{r data_wrangling, include=FALSE}
factor(opioid_df$episode)
opioid_df$opioid<-ifelse(opioid_df$CONTSUB1=="Schedule II",1,0)
sum(opioid_df$opioid)


factor(opioid_df$VDAYR)
factor(opioid_df$VMONTH)
factor(opioid_df$RACEUN)
factor(opioid_df$IMMEDR)

factor(opioid_df$PAYTYPER)
factor(opioid_df$RESIDNCE)
factor(opioid_df$REGION)
factor(opioid_df$ETHUN)
factor(opioid_df$MSA)

factor(opioid_df$CEBVD)
factor(opioid_df$EDHIV)
factor(opioid_df$NOCHRON)
factor(opioid_df$RFV1)
factor(opioid_df$DIAG1)

opioid_df$AGE<-ifelse(opioid_df$AGE=="Under one year",1, opioid_df$AGE)
opioid_df$AGE<-ifelse(opioid_df$AGE=="93 years and over",93, opioid_df$AGE)
opioid_df$DISCH7DA<-ifelse(opioid_df$DISCH7DA=="Yes",1,0)
opioid_df$Sex<-ifelse(opioid_df$Sex=="Female",1,0)

opioid_df$PAINSCALE<-ifelse(opioid_df$PAINSCALE=="Blank"|opioid_df$PAINSCALE=="Unknown",0,opioid_df$PAINSCALE)
opioid_df$PAINSCALE<-as.numeric(opioid_df$PAINSCALE)
opioid_df$AGE = as.numeric(opioid_df$AGE)
```

## Including Plots


```{r random_forests1, include=TRUE}
opioid_model = subset(opioid_df, YEAR == 2018 | YEAR == 2019)
opioid_split =  initial_split(opioid_model, prop=0.8)
traindata = training(opioid_split)
testdata  = testing(opioid_split)

load.forest = randomForest(opioid ~ DIAG1 + REGION + MSA + IMMEDR + 
                             PAYTYPER + PAINSCALE + RACEUN + male,
                           data=traindata, importance = TRUE, ntree=100)
plot(load.forest)

modelr::rmse(load.forest, testdata) 

# variable importance measures
vi = varImpPlot(load.forest, type=1)

# partial dependence plots
partialPlot(load.forest, testdata, 'PAINSCALE', las=1)

```

