---
title: "Variables"
author: ""
date: ""
output: pdf_document
---

* Time: "VMONTH","VDAYR","YEAR"


* Sociodemographics: "AGE","RESIDNCE","SEX","ETHUN","RACEUN",
"REGION","MSA","PATCODE","BDATEFL","SEXFL","ETHNICFL","RACERFL",
"ETHIM","RACER","RACERETH","AGEDAYS","AGER"

* ER Experience: "ARRTIME","WAITTIME","LOV","ARREMS"

* Payment: "PAYPRIV","PAYMCARE","PAYMCAID","PAYWKCMP","PAYSELF",
"PAYNOCHG","PAYOTH","PAYDK","PAYTYPER"

* Vital Signs:"TEMPF","PULSE","RESPR","BPSYS","BPDIAS","POPCT",
"ONO2","GCS"

* Other health indicators: "IMMEDR","PAINSCALE","SEEN72",
"DISCH7DA","PASTVIS","CEBVD","CHF","EDDIAL","EDHIV", "DIABETES","NOCHRON"

* Diagnosis: "RFV1","RFV2","RFV3","RFV13D","RFV23D","RFV33D","EPISODE",
"INJURY","INTENT","CAUSE1","CAUSE2","CAUSE3","CAUSE13D","CAUSE23D",
"CAUSE33D","DIAG1","DIAG2","DIAG3","DIAG13D","DIAG23D","DIAG33D",
"PRDIAG1","PRDIAG2","PRDIAG3","CAUSE1R","CAUSE2R",
"CAUSE3R","INTENTR","DIAG1R","DIAG2R","DIAG3R","HDDIAGR","INJR1",
"INJR2","ADVCOMP1","ADVCOMP2"

* Procedures: "DIAGSCRN","CBC","BUNCREAT","CARDENZ","ELECTROL","GLUCOSE",
"LFT","ABG","PTTINR","BLOODCX","BAC","OTHERBLD","CARDMON","EKG","HIVTEST",
"FLUTEST","PREGTEST","TOXSCREN","URINE","WOUNDCX","OTHRTEST",  "ANYIMAGE","XRAY","CATSCAN","CTHEAD","CTNHEAD","CTUNK","MRI","ULTRASND",
"OTHIMAGE","TOTDIAG","PROC","IVFLUIDS","CAST","SPLINT","SUTURE","INCDRAIN",
"FBREM","NEBUTHER","BLADCATH","PELVIC","CENTLINE","CPR","ENDOINT","OTHPROC",
"TOTPROC"

* Drugs: "MED","MED1","MED2","MED3","MED4","MED5","MED6","MED7","MED8",
"GPMED1","GPMED2","GPMED3","GPMED4","GPMED5","GPMED6","GPMED7","GPMED8",
"NUMGIV","NUMDIS","NUMMED","DRUGID1","PRESCR1","CONTSUB1","COMSTAT1",
"RX1CAT1","RX1CAT2","RX1CAT3","RX1CAT4","RX1V1C1","RX1V1C2","RX1V1C3",
"RX1V1C4","RX1V2C1","RX1V2C2","RX1V2C3","RX1V2C4","RX1V3C1","RX1V3C2",
"RX1V3C3","RX1V3C4","DRUGID2","PRESCR2","CONTSUB2","COMSTAT2","RX2CAT1",
"RX2CAT2","RX2CAT3","RX2CAT4","RX2V1C1","RX2V1C2","RX2V1C3","RX2V1C4",
"RX2V2C1","RX2V2C2","RX2V2C3","RX2V2C4","RX2V3C1","RX2V3C2","RX2V3C3",
"RX2V3C4","DRUGID3","PRESCR3","CONTSUB3","COMSTAT3","RX3CAT1","RX3CAT2",
"RX3CAT3","RX3CAT4","RX3V1C1","RX3V1C2","RX3V1C3","RX3V1C4","RX3V2C1",
"RX3V2C2","RX3V2C3","RX3V2C4","RX3V3C1","RX3V3C2","RX3V3C3","RX3V3C4",
"DRUGID4","PRESCR4","CONTSUB4","COMSTAT4","RX4CAT1","RX4CAT2","RX4CAT3",
"RX4CAT4","RX4V1C1","RX4V1C2","RX4V1C3","RX4V1C4","RX4V2C1","RX4V2C2",
"RX4V2C3","RX4V2C4","RX4V3C1","RX4V3C2","RX4V3C3","RX4V3C4","DRUGID5",
"PRESCR5","CONTSUB5","COMSTAT5","RX5CAT1","RX5CAT2","RX5CAT3","RX5CAT4",
"RX5V1C1","RX5V1C2","RX5V1C3","RX5V1C4","RX5V2C1","RX5V2C2","RX5V2C3",
"RX5V2C4","RX5V3C1","RX5V3C2","RX5V3C3","RX5V3C4","DRUGID6","PRESCR6",   
"CONTSUB6","COMSTAT6","RX6CAT1","RX6CAT2","RX6CAT3","RX6CAT4","RX6V1C1",
"RX6V1C2","RX6V1C3","RX6V1C4","RX6V2C1","RX6V2C2","RX6V2C3","RX6V2C4",
"RX6V3C1","RX6V3C2","RX6V3C3","RX6V3C4","DRUGID7","PRESCR7","CONTSUB7",
"COMSTAT7","RX7CAT1","RX7CAT2","RX7CAT3","RX7CAT4","RX7V1C1","RX7V1C2",
"RX7V1C3","RX7V1C4","RX7V2C1","RX7V2C2","RX7V2C3","RX7V2C4","RX7V3C1",
"RX7V3C2","RX7V3C3","RX7V3C4","DRUGID8","PRESCR8","CONTSUB8","COMSTAT8",
"RX8CAT1","RX8CAT2","RX8CAT3","RX8CAT4","RX8V1C1","RX8V1C2","RX8V1C3",
"RX8V1C4","RX8V2C1","RX8V2C2","RX8V2C3","RX8V2C4","RX8V3C1","RX8V3C2",
"RX8V3C3","RX8V3C4"

* Medical Staff: "NOPROVID","ATTPHYS","RESINT","CONSULT","RNLPN","NURSEPR"    
"PHYSASST","EMT","MHPROV","OTHPROV","WHOCOMP"

* Discharge characteristics: "NODISP","NOFU","RETPRN","RETREFFU","LEFTBTRI",
"LEFTATRI","LEFTAMA","DOA","DIEDED","TRANNH","TRANPSYC","TRANOTH","ADMITHOS",  
"OBSHOS","OBSDIS","OTHDISP","ADMIT","ADMTPHYS","BOARDED","LOS","HDDIAG",
"HDSTAT","ADISP","OBSSTAY"

* Survey: "PATWT","SETTYPE","CSTRATM","CPSUM","EDWT"

* ER characteristics: "OWNER","HOSPCODE","EBILLANYE","EINSELIGE",
"EMRED","EHRINSE","EDEMOGE","EPROLSTE","EPNOTESE","EMEDALGE","ECPOEE",
"ESCRIPE","EWARNE","EREMINDE","ECTOEE","EORDERE","ESETSE","ERESULTE",
"ERESEHRE","EIMGRESE","EQOCE","EIMMREGE","EPUBHLTHE","ENOTDISE", 
"ESUME","EMSGE","EWHOPRACE","EWHOOTHE","EWHONOTE","EWHOUNKE","EWHOPRACER",
"EWHOOTHER","EWHONOTER","EWHOUNKER","EXCHSUME","EXCHSUM1E","EXCHSUM2E"
"EXCHSUM3E","EXCHSUM4E","EXCHSUM5E","EXCHSUM6E","PAYHITH","PAYYRH","INCSHX",
"INCPHYS","EXPSPACE","SURGDAY","BEDCZAR","BEDDATA","HLIST","HLISTED",
"OBSUNITS","OBSDECMD","BOARD","BOARDHOS","AMBDIV","TOTHRDIVR","REGDIV",     
"ADMDIV","BEDREG","CATRIAGE","FASTTRAK","EDPTOR","DASHBORD","RFID",
"ZONENURS","POOLNURS","FULLCAP"

* Blank columns: "BLANK1","BLANK2","BLANK3","BLANK4","BLANK5","BLANK6",
"BLANK7","BLANK8"










